#!/bin/sh

case $1 in
	start)
		modprobe hello
		cp /lib/modules/`uname -r`/faulty.ko /
		start-stop-daemon -S -n faultyStart -a /bin/module_load -- faulty
		;;
	stop)
		rmmod hello
		start-stop-daemon -K -n faultyStart
		start-stop-daemon -S -n faultyStop -a /bin/module_unload
		;;
	*)
		echo "Usage is {start|stop}"
	exit 1
esac
exit 0
